[project]
name = "frontend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dash>=3.2.0",
    "python-dotenv>=1.1.1",
    "ruff>=0.14.0",
]

[tool.ruff]
line-length = 88
